OPENAI_API_KEY="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"
SF_USER='virajrawat055'
SF_PASSWORD='Snowfl@ketest011'
SF_ACCOUNT='YIHITFA-EO87783'
SF_WAREHOUSE='DBT_WH'
SF_DATABASE = 'analytics'
SF_SCHEMA = 'raw'
SF_ROLE='ACCOUNTADMIN'
