OPENAI_API_KEY="YOUR OPENAI API KEY"
SF_USER='SF USER NAME'
SF_PASSWORD='SF PASSWORD FOR ABOVE USER'
SF_ACCOUNT='SF ACCOUNT IDENTIFIER'
SF_WAREHOUSE='SF WAREHOUSE'
SF_DATABASE = 'SF DATABASE'
SF_SCHEMA = 'SF SCHEMA'
SF_ROLE='ACCOUNTADMIN'
